# Generated by Django 2.2.16 on 2022-09-11 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220911_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.5, message='Минимальное количество ингридиентов 0.5')], verbose_name='Количество'),
        ),
    ]
