# Generated by Django 2.2.16 on 2022-09-13 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220911_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1, message='Минимальное количество ингридиентов 0.1')], verbose_name='Количество'),
        ),
    ]
